# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: double-quote-string-fixer

- repo: https://github.com/fluttercommunity/import_sorter
  rev: "master"
  hooks:
  - id: flutter-import-sorter

- repo: local
  hooks:
    - id: flutter-format
      name: flutter-format
      language: system
      files: \.dart$
      entry: bash -c "flutter format --line-length=100 $(git diff --name-only --cached | grep *.dart)"
