include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    sort_unnamed_constructors_first: false
    constant_identifier_names: false
